language: minimal

sudo: required

services:
- docker

before_install:
- docker pull nimesp/esp8266

install:
- curl -L $(curl -L https://api.github.com/repos/clj/nim-esp8266-sdk/releases/latest | jq -r '.assets[].browser_download_url | select(. | test(".tar.gz"))') | tar -xz
- curl -L https://github.com/espressif/ESP8266_NONOS_SDK/archive/v3.0.3.tar.gz | tar -xz
- rm ESP8266_NONOS_SDK-3.0.3/Makefile

script:
- docker run nimesp/esp8266 nim --version
- docker run -v "$(pwd):/project" -w /project nimesp/esp8266 sh -c "make SDK_BASE=ESP8266_NONOS_SDK-3.0.3 NIM_SDK_BASE=nim-esp8266-sdk/3.0.3"

before_deploy:
- export RELEASE_DATE=${TRAVIS_TAG:8}
- docker run -v "$(pwd):/project" -w /project nimesp/esp8266 sh -c "make SDK_BASE=ESP8266_NONOS_SDK-3.0.3 NIM_SDK_BASE=nim-esp8266-sdk/3.0.3 dist"

deploy:
  provider: releases
  api_key:
    secure: uN4Sfg3mI5onJsbpG32XU7vvPbqcZnfvLQwcug4cUYRkOhRLsIEPcgtGTln9N6m+Dm/z5wUUGwxnbgX6Lb197fvATYN4cH2ZGyhjI8fD/ar9LdNrfr1QNba9C7fOyq5AXJL1nqPq6lthmMO4nLMsqZM8nnN0iUwd1g56R1LOgBaLCOwn1bIDlORuSQ6mIlVq2R8YL5eYaH/PtaohEFsouGUDE4t25VRcYNiiKVAK+npsJaZtovK4LmcSbQ2w8be0H2IBZCNe+DKO6eTA/i/p5Ns5J1rtS5BCfbylgMjs/LR/aPAmpC330YLwu8rHDL5daXuESi3hrxeTYC5DZAaX+7wzz9HvzsMka3rKQLzoXI40qqoK36L5jK7D6K45Zn/E8kZBs3eokodS8gzVTVnheVE2zUGnusj2YYBK2kEGxmCjg1C1WU1WUeehIq47CAS+z5GDfAwhMDGvmUXCK7Co8Dc0N1hhtgYNm+P1BAEoXaOGr4Xz6nmu6/GWiP5KcYr1PE7Jtvm+kKYtmGyP+SDgClXsi4umKp+GInB6RgZ1IW0Vxu0K1hio0clvPdp9iRSDd1YSUiNnwRCvGbW92sTcoa/sG1H0fb9fD5aw/U+Wj7PyXrxElGckp7L82OdkurO35YhGdBx1F/vUu0CQGVwm6TrU+AfGJIb9gfO4UJmiIQ0=
  file_glob: true
  file: nim_esp8266_examples-*
  edge: true
  release_notes_file: 'release-notes/${RELEASE_DATE}.md'
  name: "Release ${RELEASE_DATE}"
  skip_cleanup: true
  on:
    repo: clj/nim-esp8266-examples
    tags: true
